name: Publish
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.23.6
          run_install: true

      - name: Lint source
        run: |
          pnpm lint

      - name: Build package
        run: |
          pnpm build

      - name: 'Consume changesets'
        if: github.event_name == 'push' && github.repository == 'ivandotv/nextjs-workbox-config' && github.ref == 'refs/heads/main'
        uses: changesets/action@v1
        id: 'changesets'
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          commit: version bump
          title: Next release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
